name: BannableDeaths
main: com.resbah.DeathBan.DeathBan
version: 0.1 by resba
commands:
    bdunban:
        description: Hardcode Unban
        usage: /bdunban [user]
permissions:
    BannableDeaths.*:
        description: Allows access to all commands
        children:
            BannableDeaths.bypass:
                description: If true, allows user to bypass Ban on Death
                default: false
            BannableDeaths.unban:
                description: If true, allows user to use /bdunban
                default: false